### ISSUE TITLE
Question: what is your setup for BuckleScript?

### ISSUE THREAD

**Issue by dylanirlbeck** [jordwalke/vim-reasonml#23]
@jordwalke This plugin looks awesome, great job! I don't have an issue with this plugin, though I do have a question (and I thought the info might help other Vimmers).

I noticed that the plugin is strictly for native projects, so I wanted to ask what your setup is for BuckleScript projects? At the moment, I'm using `coc` + `ocaml-lsp` + `ale` for both BuckleScript and native, and it's been working pretty great.

Thanks in advance!

**Comment by anmonteiro** [comment]
I use this plugin with BuckleScript, you just need to have a merlin binary available compiled against 4.06.

I changed it slightly in my setup so that it works well outside esy: https://github.com/anmonteiro/dotfiles/blob/083f1cd5abba875bf027abc71120837bd57b99ab/nix/homies/nvim/ftplugin/ocamlOrReason.vim#L40-L44
